# site settings
title: Forty
subtitle: by HTML5 UP
email: "insoel@gmail.com"
description: "Game Developer Portefolio"
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: "Ianis Arquissandas"
street_address: 
city: "Lisbon"
state: 
zip_code:
country: "Portugal"
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
