# Site settings
title: Ianis Arquissandas | Portfolio
description: A Game Developer Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ianis Arquissandas
user_description: Hello, I'm Ianis Arquissandas, and I am a Game Developer and Programmer in Portugal.
					I'm currently at my last year in college, taking a Videogame Bachelor degree, at Universidade Lusofona.
					I've been in love with games since I can remember, as such I decided to pursue a career related to games.
					At 12 I started making custom maps and messing around with models for some of Valve's games, using their Hammer software. I also learned quite a bit of blender around that age.
					In college I found my passion in programming video games. 
					I learned as much as I could using the Unity Engine, I also learned some programming languages, such as some basic knowledge in C and JavaScript and a very extensive knowledge of C# which is my main programming language.
					I studied design patterns, databases and artificial inteligence for video games.
user_title: Game Developer / Programmer
email: insoel@gmail.com
github_username:  insoel

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
